sonicdplcindex:
		ptr dplc_Blank
		ptr dplc_Walk26
		ptr dplc_Walk36
		ptr dplc_Stand
		ptr dplc_Wait1
		ptr dplc_Wait2
		ptr dplc_Wait3
		ptr dplc_LookUp
		ptr dplc_Walk11
		ptr dplc_Walk12
		ptr dplc_Walk13
		ptr dplc_Walk14
		ptr dplc_Walk15
		ptr dplc_Walk43
		ptr dplc_Walk42
		ptr dplc_Walk41
		ptr dplc_Walk35
		ptr dplc_Walk34
		ptr dplc_Walk33
		ptr dplc_Walk32
		ptr dplc_Walk31
		ptr dplc_Walk25
		ptr dplc_Run13
		ptr dplc_Roll3
		ptr dplc_Spring
		ptr dplc_Shrink3
		ptr dplc_Shrink4
		ptr dplc_Shrink5
		ptr dplc_Float5
		ptr dplc_Float6
		ptr dplc_Injury
		ptr dplc_GetAir
		ptr dplc_WaterSlide
		ptr dplc_BubStand
		ptr dplc_Surf
		ptr dplc_Push4
		ptr dplc_Push3
		ptr dplc_Push2
		ptr dplc_Push1
		ptr dplc_Leap2
		ptr dplc_Leap1
		ptr dplc_Hang2
		ptr dplc_Hang1
		ptr dplc_Roll4
		ptr dplc_Run14
		ptr dplc_Run21
		ptr dplc_Roll5
		ptr dplc_Warp1
		ptr dplc_Run22
		ptr dplc_Warp2
		ptr dplc_Run23
		ptr dplc_Run24
		ptr dplc_Warp3
		ptr dplc_Warp4
		ptr dplc_Run31
		ptr dplc_Run32
		ptr dplc_Stop1
		ptr dplc_Stop2
		ptr dplc_Run33
		ptr dplc_Run34
		ptr dplc_Duck
		ptr dplc_Balance1
		ptr dplc_Run41
		ptr dplc_Burnt
		ptr dplc_Balance2
		ptr dplc_Run42
		ptr dplc_Walk44
		ptr dplc_Walk16
		ptr dplc_Walk21
		ptr dplc_Walk22
		ptr dplc_Walk23
		ptr dplc_Walk24
		ptr dplc_Run12
		ptr dplc_Roll2
		ptr dplc_Float4
		ptr dplc_Shrink2
		ptr dplc_Shrink1
		ptr dplc_Death
		ptr dplc_Drown
		ptr dplc_Float1
		ptr dplc_Run43
		ptr dplc_Walk45
		ptr dplc_Walk46
		ptr dplc_Run11
		ptr dplc_Roll1
		ptr dplc_Float3
		ptr dplc_Float2
		ptr dplc_Run44

